### PR TITLE
Fix bug of detector task calls failing if no state index

### LINKED ISSUE #109: Can't show detector list if no detector started
On a new cluster, create a detector but don't start realtime/historical detection. Go to detector list page, it won't show the detector. Check backend OpenSearch log, found such error

```
[2021-10-28T22:51:29,301][ERROR][o.o.a.u.RestHandlerUtils ] [integTest-0] Wrap exception before sending back to user
org.opensearch.index.IndexNotFoundException: no such index [.opendistro-anomaly-detection-state]
        at org.opensearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.indexNotFoundException(IndexNameExpressionResolver.java:959) ~[opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:896) ~[opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:852) ~[opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:231) ~[opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:207) ~[opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.search.TransportSearchAction.resolveLocalIndices(TransportSearchAction.java:634) ~[opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:662) ~[opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.search.TransportSearchAction.executeLocalSearch(TransportSearchAction.java:541) ~[opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.search.TransportSearchAction.lambda$executeRequest$3(TransportSearchAction.java:333) ~[opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.ActionListener$1.onResponse(ActionListener.java:76) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:127) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:100) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:376) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:259) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:120) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:192) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:168) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:96) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:99) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:88) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:428) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.client.support.AbstractClient.search(AbstractClient.java:561) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.ad.transport.handler.ADSearchHandler.validateRole(ADSearchHandler.java:69) [opensearch-anomaly-detection-1.1.0.0-SNAPSHOT.jar:1.1.0.0-SNAPSHOT]
        at org.opensearch.ad.transport.handler.ADSearchHandler.search(ADSearchHandler.java:57) [opensearch-anomaly-detection-1.1.0.0-SNAPSHOT.jar:1.1.0.0-SNAPSHOT]
        at org.opensearch.ad.transport.SearchADTasksTransportAction.doExecute(SearchADTasksTransportAction.java:35) [opensearch-anomaly-detection-1.1.0.0-SNAPSHOT.jar:1.1.0.0-SNAPSHOT]
        at org.opensearch.ad.transport.SearchADTasksTransportAction.doExecute(SearchADTasksTransportAction.java:24) [opensearch-anomaly-detection-1.1.0.0-SNAPSHOT.jar:1.1.0.0-SNAPSHOT]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:192) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:168) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:96) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:99) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:88) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:428) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.ad.rest.AbstractSearchAction.lambda$prepareRequest$0(AbstractSearchAction.java:88) [opensearch-anomaly-detection-1.1.0.0-SNAPSHOT.jar:1.1.0.0-SNAPSHOT]
        at org.opensearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:123) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.rest.RestController.dispatchRequest(RestController.java:271) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.rest.RestController.tryAllHandlers(RestController.java:353) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.rest.RestController.dispatchRequest(RestController.java:204) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:332) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:397) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:322) [opensearch-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:55) [transport-netty4-client-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.opensearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:41) [transport-netty4-client-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at org.opensearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:71) [transport-netty4-client-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.59.Final.jar:4.1.59.Final]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

Looks this error happens when detector list page calls search task API.
Search task API returns such error if no detector started.
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [.opendistro-anomaly-detection-state]",
        "index" : ".opendistro-anomaly-detection-state",
        "resource.id" : ".opendistro-anomaly-detection-state",
        "resource.type" : "index_or_alias",
        "index_uuid" : "_na_"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [.opendistro-anomaly-detection-state]",
    "index" : ".opendistro-anomaly-detection-state",
    "resource.id" : ".opendistro-anomaly-detection-state",
    "resource.type" : "index_or_alias",
    "index_uuid" : "_na_"
  },
  "status" : 404
}
```

### PR DESCRIPTION
**Pull request by ohltyler**
Signed-off-by: Tyler Ohlsen <ohltyler@amazon.com>

### Description
Fixes an edge case where calls to the search task API will fail if the `.opendistro-anomaly-detection-state` system index doesn't exist, which will only happen on a fresh cluster that has never ran any detector job (once any job is ran,the system index is created).

This fixes all places where the search task API is called on server-side, and wraps in a separate try/catch to suppress any `index_not_found_exception`, so that the rest of the logic can be executed normally.

The side effects of this bug (which are now fixed):
1. Detector list will fail to show any detectors, shows error toast saying error getting all detectors
2. Detector details pages will fail, shows error toast saying error getting detector

### Issues Resolved
Closes #109 

### Check List
- [x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: server/routes/ad.ts [hunk 1]
```diff
@@ -260,19 +260,29 @@ export default class AdService {
...
+          .callAsCurrentUser('ad.searchTasks', {
+            body: getLatestTaskForDetectorQuery(detectorId, true),
+          });
+        historicalTasksResponse = await this.client
+          .asScoped(request)
+          .callAsCurrentUser('ad.searchTasks', {
+            body: getLatestTaskForDetectorQuery(detectorId, false),
+          });
+      } catch (err) {
+        if (!isIndexNotFoundError(err)) {
```
Comment (amitgalitz) [inline server/routes/ad.ts:279]: Are there any critical indices that could be not found other then `.opendistro-anomaly-detection-state` where you would want indexNotFoundError to be displayed or anyway giving an error on getting detector list for an issue with search always a 'buggy' output.

Comment (ohltyler) [reply server/routes/ad.ts:279]: Not for this specific call. If there was other critical indices missing they would already get caught and propagated as an error in the previous calls, such as fetching the initial detector info.

Since this call is just for searching the tasks which is querying the `.opendistro-anomaly-detection-state` index, it should be ok. Prefer to not hardcode many system indices on the frontend, since I would consider it more to be a backend implementation detail.

**Review by ylwu-amzn — APPROVED** [review]

File: server/routes/ad.ts (hunk 1 above)
Comment (amitgalitz) [reply server/routes/ad.ts:279]: Makes sense, sounds good to me.

**Review by amitgalitz — APPROVED** [review]
